# theme: jekyll-theme-minimal
remote_theme: jekyll/minima
ignore_theme_config: true

url: "https://thosgood.com/translations/"

title: Maths translations
description: English translations of mathematical articles, lecture notes, etc.
author:
  name: Tim Hosgood
  # email: "tim.hosgood@posteo.net"
  website: "https://thosgood.com"
twitter_username: tim_hosgood


minima:
  social_links:
    twitter: tim_hosgood
