# theme: jekyll-theme-minimal
remote_theme: jekyll/minima
ignore_theme_config: true
title: Maths translations
description: English translations of mathematical articles, lecture notes, etc.
logo: /images/puffin.png
author:
  name: Tim Hosgood
  email: "tim.hosgood@posteo.net"